baseURL = "/"
languageCode = "en-us"
title = "Tim Pittman"
theme = "hugo-theme-basic"
googleAnalytics = "UA-102047143-1"
enableEmoji = true 
copyright = "<a href='https://twitter.com/pittman021'>pittman021</a>."
description = "Basic personal site theme styled with minimal tachyons, syntax highlighting, and blog series configuration."
enableRobotsTXT = true
canonifyURLs = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  description = "Director of client programs <a href='bazaarvoice.com'>bazaarvoice</a>. Formerly customer success <a href='sumo.com'>Sumo.com</a>. </br></br> Host of the Valencia CF Podcast 🎤"
  titleEmoji = ""
  twitter = "pittman021"

[Permalinks]
  post = "post/:slug"
  
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true