baseURL = "/"
languageCode = "en-us"
title = "Tim Pittman"
theme = "hugo-theme-basic"
googleAnalytics = "UA-102047143-1"
enableEmoji = true 
copyright = "<a href='https://twitter.com/pittman021'>pittman021</a>."
description = "Basic personal site theme styled with minimal tachyons, syntax highlighting, and blog series configuration."
enableRobotsTXT = true
canonifyURLs = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  description = "Director of Client Programs <a href='bazaarvoice.com'>bazaarvoice</a>. </ br> Formerly Head of Customer Success at <a href='sumo.com'>sumo.com</a>. Host of the <a href='https://twitter.com/AmuntPodcast'> Valencia CF Podcast</a> 🎤"
  titleEmoji = ""
  twitter = "pittman021"

[Permalinks]
  post = "post/:slug"
  
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true