baseURL = "/"
languageCode = "en-us"
title = "Tim Pittman"
theme = "hugo-theme-basic"
googleAnalytics = "UA-102047143-1"
enableEmoji = true 
copyright = "<a href='https://twitter.com/pittman021'>pittman021</a>."
description = "Basic personal site theme styled with minimal tachyons, syntax highlighting, and blog series configuration."
enableRobotsTXT = true
canonifyURLs = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  description = "<p>Currently customer retention @bazaarvoice.</p><p>Formerly customer success @sumome.</p><p> Creating things on the side. 🚀 </p>"
  titleEmoji = ":clap:"
  twitter = "pittman021"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "posts"
  url = "posts/"

[[params.menu]]
  name = "projects"
  url = "projects/"
  
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true